---
title: "Note - Data Munge"
author: "Sam Thorold"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height=3)
```

```{r libraries, message=FALSE, warning=FALSE}
library(data.table)
library(dplyr)
library(dtplyr)
library(ggplot2)
library(knitr)
```

# CRSP

```{r read.crsp}
# fread much faster than read.csv
# colClasses='character' prevents scary message about losing data due to
# changing column types part way through reading the data
crsp = fread(
    "C:/Data/CRSP/CRSP_196001_201612_d.csv", colClasses='character', showProgress=FALSE
)
```

```{r}
crsp = crsp %>% filter(SHRCD %in% c(10, 11)) %>% filter(EXCHCD %in% c(1, 2, 3))

crsp$SHRCD = NULL  # sharecode no longer needed

setnames(crsp,
         c("EXCHCD", "SICCD", "DLRET", "RET", "PRC", "SHROUT", "vwretd"),
         c("Exchange", "Industry", "dl.ri", "ri", "price", "shares", "rm"))

crsp$PERMNO = factor(crsp$PERMNO)
crsp$Date = as.Date(crsp$date, "%Y%m%d")
crsp$Exchange = factor(crsp$Exchange,
                       levels=c("1","2","3"),
                       labels=c("NYSE", "AMEX", "NASDAQ"))
crsp$Industry = factor(crsp$Industry)
crsp$dl.ri = as.numeric(crsp$dl.ri)
crsp$price = as.numeric(crsp$price)
crsp$ri = as.numeric(crsp$ri)
crsp$shares = as.numeric(crsp$shares) / 1000
crsp$rm = as.numeric(crsp$rm)

summary(crsp)
```

There should be no duplicate $PERMNO$-$date$ pairs
(`r format(sum(duplicated(crsp[,c("PERMNO", "date")])), big.mark=" ")` found).
CRSP data has `r format(nrow(crsp), big.mark=" ")` rows and
`r format(ncol(crsp), big.mark=" ")` columns.

```{r duplicates, include=FALSE}
# duplicated will omit return FALSE for the first instance of a duplicated row
# calling from the top and the bottom ensure all instances are caught
pairs.ix = duplicated(crsp[, c("PERMNO", "date")]) |
           duplicated(crsp[, c("PERMNO", "date")], fromLast=TRUE)
if (sum(pairs.ix)>0){
    kable(head(crsp[pairs.ix], n=10), digits=2, caption="Duplicates")
    crsp = crsp %>% filter(!duplicated(crsp[,c("PERMNO", "date")]))
}
```

```{r head, echo=FALSE}
kable(head(crsp), digits=2, caption="CRSP")
```

## Market Equity

Fama and French define Market Equity as

# COMPUSTAT

```{r, read.compustat}
# Don't need to use colClasses here
comp = fread("C:/Data/CRSP/COMP_196001_201612_c.csv", showProgress=FALSE)
```

```{r}
comp$GVKEY = NULL

setnames(comp, c("LPERMNO"), c("PERMNO"))

comp$PERMNO = factor(comp$PERMNO)
comp$Date = as.Date(as.character(comp$datadate), "%Y%m%d")
```


